a=input("Mi a neved? ")
b=int(input("Hány éves vagy? "))
print("A maga életkora ",b,"és az ön neve ",a)
s=int(input("milyen indős anyukád? "))
g=int(input("milyen indős apukád? "))
print("anyukád ",s-b," volt mikor megszülettél")
print("apukád ",g-b," volt mikor megszülettél")